name: Validate Gradle Wrapper

on:
  pull_request:
  push:
    paths: [ '**.jar' ]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1
